server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  prefix: /api   #添加路由前缀
  routes:
    item-service: /item/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order-service/**
    upload-service:
      path: /upload/**
      service: upload-service
      strip-prefix: false
    search-service: /search/**
  sensitive-headers:
  add-host-header: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000  #设置熔断超时时长：7000ms
ribbon:
  connetTimeout: 500  #ribbon链接超时时长
  readTimeout: 5000   #ribbon读取超时时长
  MaxAutoRetries: 0   #当前服务重试次数
  MaxAutoRetriesNextServer: 0  #切换服务重试次数

ly:
  jwt:
    pubKeyPath: /Users/bystander/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
    - /api/auth
    - /api/search
    - /api/user/register
    - /api/user/check
    - /api/user/code
    - /api/item

